apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wind-turbine-demo-pipeline
spec:
  description: | 
    This pipeline builds the wind-turbine-demo
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: repo-branch
      type: string
      description: The branch to be used.
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: node-cache
    - name: npm-repo
    - name: maven-repo
    - name: dockerconfig-ws
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-branch)
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven-cached
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_IMAGE
          value: quay.io/quarkus/ubi-quarkus-native-s2i:22.2-java17
          #value: 'maven:3.8.6-openjdk-18'
        - name: CONTEXT_DIR
          value: "."
        - name: PROXY_PROTOCOL
          value: http
        - name: GOALS
          value:
            #- -B
            - package
            - "-Dquarkus.quinoa.package-manager-install.install-dir=$(workspaces.node-cache.path)"
            - "-Dquarkus.quinoa.package-manager-command.install-env.NPM_CONFIG_CACHE=$(workspaces.npm-repo.path)"
            #- '-DskipTests'
            #- '-Dnative'
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-repo
        - name: node-cache
          workspace: node-cache
        - name: npm-repo
          workspace: npm-repo
    - name: ui-buildah
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: ui
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/wind-turbine-demo:$(context.pipelineRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: ui-skopeo-copy
      taskRef:
        name: skopeo-copy
      runAfter:
        - ui-buildah
      params:
        - name: srcImageURL
          value: docker://registry-1.docker.io/domenicopiol/wind-turbine-demo:$(context.pipelineRun.uid)
        - name: destImageURL
          value: docker://registry-1.docker.io/domenicopiol/wind-turbine-demo:latest
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      workspaces:
        - name: images-url
          workspace: shared-workspace
