apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wind-turbine-demo-pipeline
spec:
  description: | 
    This pipeline builds the wind-turbine-demo
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: repo-branch
      type: string
      description: The branch to be used.
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: dockerconfig-ws
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-branch)
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_IMAGE
          value: quay.io/quarkus/ubi-quarkus-native-s2i:22.2-java17
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -B
            - package
            - '-DskipTests'
            - '-Dnative'
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: ui-buildah
      taskRef:
        name: buildah
      runAfter:
        - maven-run
      params:
        - name: CONTEXT
          value: ui
        - name: IMAGE
          value: registry-1.docker.io/domenicopiol/wind-turbine-demo:$(context.pipelineRun.uid)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
    - name: ui-skopeo-copy
      taskRef:
        name: skopeo-copy
      runAfter:
        - ui-buildah
      params:
        - name: srcImageURL
          value: docker://registry-1.docker.io/domenicopiol/wind-turbine-demo:$(context.pipelineRun.uid)
        - name: destImageURL
          value: docker://registry-1.docker.io/domenicopiol/wind-turbine-demo:latest
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      workspaces:
        - name: images-url
          workspace: shared-workspace
