apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: wind-turbine-demo-pipeline-run
spec:
  pipelineRef:
    name: wind-turbine-demo-pipeline
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
    - name: dockerconfig-ws
      secret:
        secretName: dockerconfig-secret
  params:
    - name: repo-url
      value: https://github.com/domenico-piol/wind-turbine-demo
    - name: repo-branch
      value: domenico